#!/bin/sh
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:       Set up iptables rules
### END INIT INFO

# Author: Romain Libaert <r.libaert@gmail.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.


# VARIABLES
DAEMON=iptablesd

IPT=/sbin/iptables
IPTREST=/sbin/iptables-restore
IPTSAVE=/sbin/iptables-save

FOLDERSAV=/etc/iptables/
FILESAV=${FOLDERSAV}rules
### END VARIABLES


. /lib/lsb/init-functions

case "$1" in
start)
	log_daemon_msg 'Restoring iptables rules' $DAEMON
	if [ -e /var/run/iptables ]
	then
		log_end_msg 0
		log_action_msg "$0 already started"
		exit 1
	else
		touch /var/run/iptables
	fi

	if [ -f $FILESAV ]
	then
		$IPTREST < $FILESAV
		log_end_msg 0
	else
		log_end_msg 1
		log_failure_msg "Nothing to restore at $FILESAV"
	fi
	;;

stop)
	log_daemon_msg 'Stopping all iptables rules' $DAEMON
	if [ -e /var/run/iptables ]
	then
		$IPT -F
		$IPT -X
		$IPT -P INPUT ACCEPT
		$IPT -P FORWARD ACCEPT
		$IPT -P OUTPUT ACCEPT
		rm /var/run/iptables
		log_end_msg 0
	else
		log_end_msg 0
		log_action_msg "$DAEMON already stopped"
		exit 1;
	fi
	;;

restart)
	$0 stop
	$0 start
	;;

show)
	log_action_msg "Showing running iptables rules"
	$IPT -L -v
	;;

status)
	if [ -e /var/run/iptables ]
	then
		log_success_msg "$DAEMON is running"
	else
		log_failure_msg "$DAEMON is not running"
	fi
	;;

save)
	log_daemon_msg "Saving current rules to $FILESAV" $DAEMON
	if [ ! -d $FOLDERSAV ]
	then
		mkdir $FOLDERSAV
	fi
	$IPTSAVE > $FILESAV
	log_end_msg 0
	;;

*)
	log_action_msg "Usage: $0 {start|stop|restart|status|save|show}"
	;;
esac

exit 0
